services:


  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - telemusic_default

  backend:
    build: .
    container_name: nestjs-backend
    restart: always
    environment:
      DATABASE_URL: mysql://root:root@news-rewards-db:3306/music_db
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: 1000
      WATCHPACK_POLLING: "true"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - ./tmp:/tmp
    command: sh -c "npx prisma generate && npm run start:dev"
    networks:
      - news-reward-be_laravel
      - telemusic_default
    depends_on:
      - redis

  prisma-studio:
    image: node:22-alpine
    container_name: prisma-studio
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_URL: mysql://root:root@news-rewards-db:3306/music_db
    command: npx prisma studio --port 5555 --schema=prisma/schema.prisma
    ports:
      - "5555:5555"
    networks:
      - news-reward-be_laravel
  

  bullmq-worker:
    build: .
    container_name: bullmq-worker
    command: npm run start:worker
    volumes:
      - .:/usr/src/app 
      - ./tmp:/tmp
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - telemusic_default
      - news-reward-be_laravel

networks:
  news-reward-be_laravel:
    external: true

  telemusic_default:
    external: true