version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    networks:
      - telemusic_default
    ports:
      - "6379:6379"

  backend:
    image: mandalayads/telemusic-api:latest
    container_name: nestjs-backend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && node dist/main.js"
    depends_on:
      - redis
    networks:
      - telemusic_default

  worker:
    image: mandalayads/telemusic-worker:latest
    container_name: bullmq-worker
    restart: always
    env_file:
      - .env
    command: node dist/worker.js
    depends_on:
      - redis
    networks:
      - telemusic_default

networks:
  telemusic_default:
    external: true