services:
  backend:
    build: .
    container_name: nestjs-backend
    user: "1000:1000"
    restart: always
    environment:
      DATABASE_URL: mysql://root:root@dk-database:3306/music_db
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: 1000
      WATCHPACK_POLLING: "true"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npx prisma generate && npm run start:dev"
    networks:
      - telemusic_net

  prisma-studio:
    image: node:22-alpine
    container_name: prisma-studio
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_URL: mysql://root:root@dk-database:3306/music_db
    command: npx prisma studio --port 5555 --schema=prisma/schema.prisma
    ports:
      - "5555:5555"
    networks:
      - telemusic_net

networks:
  telemusic_net:
    external: true